
service: sls-example

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  stage: dev
  profile: serverless-admin
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello
    events:
      - http:
        path: hello
        method: get
